version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node14.16.0-chrome90-ff88'

workflows:
  build:
    jobs:
      - cypress/run:
          verify-command: yarn cypress verify
          store_artifacts: true
          executor: with-chrome
          browser: chrome
