version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node14.16.0-chrome90-ff88'
  with-firefox:
    docker:
      - image: 'cypress/browsers:node14.16.0-chrome89-ff86'
  with-edge:
    docker:
      - image: 'cypress/browsers:node14.10.1-edge88'

workflows:
  build:
    jobs:
      - cypress/run:
          config: record_key
          name: Chrome
          verify-command: yarn cypress verify
          store_artifacts: true
          executor: with-chrome
          browser: chrome
          group: chrome
          record: true
      - cypress/run:
          config: record_key
          name: Firefox
          verify-command: yarn cypress verify
          store_artifacts: true
          executor: with-firefox
          browser: firefox
          group: firefox
          record: true
      - cypress/run:
          config: record_key
          name: Edge
          verify-command: yarn cypress verify
          store_artifacts: true
          executor: with-edge
          browser: edge
          group: edge
          record: true


